version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - global

  web:
    restart: always
    build:
      dockerfile: ./Dockerfile-dev
      context: ./back/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=somethingsupersecret
      - BASE_URL=http://0.0.0.0:3000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DEFAULT_FROM_EMAIL=hello@chiefonboarding.com
    volumes:
      - ./back:/app
    depends_on:
      - db
    networks:
      - global

  nuxt:
    image: node:latest
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    command: bash -c "cd /app && npm install && cd /app/node_modules/fibers/ && npm install && cd /app && npm install -g nuxt && npm run dev"
    networks:
      - global

volumes:
  pgdata:

networks:
  global:
