name: Release to test-deploy repo 
on:
  pull_request:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build source
      env:
        BASE_URL: /
      run: |
        cd front
        npm install
        npx nuxt build
        node ./postinstall
    - name: Cleaning up repo 
      run: |
        rm -rf front/
    - name: Git push to deploy repo 
      run: |
        git config --global user.name 'ChiefOnboarding'
        git config --global user.email 'noreply@chiefonboarding.com'
        git add -A 
        git commit -m "Deploy" 
        git status
        git push -f origin HEAD:test-deploy
